remote_theme: pages-themes/merlot
title: Choose Your Adventure
tagline: Do quests, not goals.
ddescription: Chris Barlow creates quest-based experiences for communities and collaboration. Co-founder of the Agentics Foundation NZ chapter.
url: https://chrisbarlow.nz
lang: en_NZ

author:
  name: Chris Barlow
  url: https://chrisbarlow.nz

social:
  name: Chris Barlow
  links:
    - https://www.linkedin.com/in/cgbarlow/
    - https://github.com/cgbarlow
    - https://unchartedquests.substack.com/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
